---
title: "Final Project"
author: "Shane Taylor shanemt2@illinois.edu; Zhouning Ma zm11@illinois.edu; Kevin Mackie"
date: "7/28/2019"
output: html_document
---

# The is not the final format, we should reformat/edit each section

# Introduction
- What is this data? 
- Where did it come from? 
- What are the variables? 
- Why is it interesting to you?
- Why are you creating a model for this data? 
- What is the goal of this model?

# Methods
This section should contain any information about data preparation that is performed to the original data before modelling. Then you will apply methods seen in class, which may include some of the following but are not limited to:

- Multiple linear regression
- Dummy variables
- Interaction
- Residual diagnostics
- Outlier diagnostics
- Transformations
- Polynomial regression
- Model selection
Your task is not to use as many methods as possible. Your task is to use appropriate methods to find a good model that can correctly answer a question about the dataset, and then to communicate your result effectively.


# Results
The results section should contain numerical or graphical summaries of your results. You should report a final model you have chosen. There is not necessarily one, singular correct model, but certainly some methods and models are better than others in certain situations. You may use any methods we studied this semester to complete this task, and provide evidence that your final choice of model is a good one.


# Discussion
The discussion section should contain discussion of your results and should frame your results in the context of the data. How is your final model useful?


# Appendix
The appendix section should contain code and analysis that is used, but that may clutter the report or is not directly related to the choice of model.






# Something we may use below
- Building the Model 
- Colinearity 
- Removing influential data points
- Transformations
- Alternative models
- Model Comparison
- Model Validation
- AIC/BIC Testing
- LOOCV_RMSE
